name: CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Granting private modules access
      run: |
        git config --global url."https://${{ secrets.BACKEND_TESTS_TOKEN }}:x-oauth-basic@github.com/parsyl".insteadOf "https://github.com/parsyl"

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Test
      run: go test -v ./...

    - uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        fields: repo,author,ref
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_BACKEND_CI_WEBHOOK }}
      if: always()
